### ISSUE TITLE
Auto format option in package settings

### ISSUE THREAD

**Issue by RamoFX** [ayame113/atom-ide-deno#1]
Hello,

I am really happy to see first atom deno package.

But I found auto-formating code very annoying. Can enabling / disabling of this feature be implemented?

Can I also have contact to you? We maybe can discuss something about this package functionality.

Roman

**Comment by ayame113** [comment]
Thank you for your comment.
This extension doesn't have auto-formating yet. When implementing the auto-formating feature, I would like to implement the enable / disable feature as well.

I am new to both English and github. Feel free to comment.

**Comment by RamoFX** [comment]
I am sorry, I can speak only Russian, Czech and English :(

Here you can see the video demonstration. Maybe it have some conflict with another package.

https://user-images.githubusercontent.com/24795597/108626952-2d891c00-7453-11eb-8a10-f506df72f844.mp4

**Comment by RamoFX** [comment]
Look, I disabled all the packages, but now it is working as expected. Really weird.

I will do some research and give feedback.

https://user-images.githubusercontent.com/24795597/108627252-cec4a200-7454-11eb-9568-cb547a81640a.mp4

**Comment by RamoFX** [comment]
I am very sorry, it is my bad, it was mistake in atom-ide-ui configuration.

The strange thing is that I had enabled `format on save` option, but it never worked, only when I installed atom-ide-deno package.
