### ISSUE TITLE
Cannot import using URL or import map

### ISSUE THREAD

**Issue by RamoFX** [ayame113/atom-ide-deno#3]
Hello!

I can't import some typescript module using URL (for example: `import { gray, blue, yellow, red, bold } from 'https://deno.land/std/fmt/colors.ts'`) or can't use import map as shown below in screencast.

#### Screencast: 
https://user-images.githubusercontent.com/24795597/108634844-f24f1300-747b-11eb-9e24-9ab6d9112ca1.mp4

Will it be implemented or I am missing something?

Thanks!

**Comment by ayame113** [comment]
Thank you for your report.

Support for importMap has been added in today's release. 👍

**Comment by RamoFX** [comment]
Okay, thank you!
