### ISSUE TITLE
Cannot find name 'Deno'

### ISSUE THREAD

**Issue by RamoFX** [ayame113/atom-ide-deno#4]
Hello!

I have an issue with Deno. There is errors that `Cannot find name 'Deno'` and it has type `any`.

#### Screencast
https://user-images.githubusercontent.com/24795597/108635143-eebc8b80-747d-11eb-89de-62a864351034.mp4

Will it be implemented or I am missing something?

Thanks!

**Comment by ayame113** [comment]
Thank you for reporting.

There are `atom-ide-javascript` package for Node.js and `atom-ide-deno` package for Deno. For Deno code, turn off the Node.js package.

(I should have written this in the Readme)

**Comment by RamoFX** [comment]
Yeah. you are right. It's a shame, that there is no package, that switches current IDE between Node, Deno, regular Typescript and Javascript IDE's. Thank you, didn't noticed!
